export const mockProducts = [
  {
    id: 'p1',
    name: '헬로키티 롱다리키링',
    option: '핑크',
    price: 5000,
    stock: 100,
  },
  {
    id: 'p2',
    name: '헬로키티 롱다리키링',
    option: '화이트',
    price: 5000,
    stock: 80,
  },
  {
    id: 'p3',
    name: '헬로키티 퀄팅파우치',
    option: '핑크',
    price: 12000,
    stock: 65,
  },
  {
    id: 'p4',
    name: '헬로키티 퀄팅파우치',
    option: '베이지',
    price: 12000,
    stock: 50,
  },
  {
    id: 'p5',
    name: '헬로키티 물방울스티커',
    option: '기본',
    price: 3300,
    stock: 90,
  },
  {
    id: 'p6',
    name: '쿠로미 키링세트',
    option: '블랙',
    price: 12900,
    stock: 75,
  },
  {
    id: 'p7',
    name: '쿠로미 키링세트',
    option: '퍼플',
    price: 12900,
    stock: 60,
  },
  {
    id: 'p8',
    name: '쿠로미 미니파우치',
    option: '블랙',
    price: 8900,
    stock: 55,
  },
  {
    id: 'p9',
    name: '마이멜로디 에코백',
    option: '핑크',
    price: 8900,
    stock: 80,
  },
  {
    id: 'p10',
    name: '마이멜로디 에코백',
    option: '화이트',
    price: 8900,
    stock: 70,
  },
  {
    id: 'p11',
    name: '마이멜로디 스티커팩',
    option: 'A세트',
    price: 4500,
    stock: 100,
  },
  {
    id: 'p12',
    name: '시나모롤 피규어',
    option: '블루',
    price: 9900,
    stock: 45,
  },
  {
    id: 'p13',
    name: '시나모롤 키링',
    option: '블루',
    price: 6500,
    stock: 85,
  },
  {
    id: 'p14',
    name: '시나모롤 파우치',
    option: '스카이블루',
    price: 11000,
    stock: 50,
  },
  {
    id: 'p15',
    name: '폼폼푸린 요리사피규어',
    option: '옐로우',
    price: 7400,
    stock: 60,
  },
  {
    id: 'p16',
    name: '폼폼푸린 키링',
    option: '옐로우',
    price: 5500,
    stock: 75,
  },
  {
    id: 'p17',
    name: '포차코 미니파우치',
    option: '그린',
    price: 8500,
    stock: 55,
  },
  {
    id: 'p18',
    name: '바드바드마루 키링',
    option: '화이트',
    price: 6000,
    stock: 70,
  },
  {
    id: 'p19',
    name: '키키라라 스티커세트',
    option: '파스텔',
    price: 4800,
    stock: 90,
  },
  {
    id: 'p20',
    name: '몬치치 피규어S',
    option: '브라운',
    price: 13400,
    stock: 40,
  },
]

export const mockRooms = [
  {
    id: 'room-1',
    title: '2월 15일 저녁 특가방',
    createdAt: '2026-02-15T18:00:00Z',
    status: 'active',
    orderCount: 12,
    totalAmount: 156700,
  },
  {
    id: 'room-2',
    title: '2월 10일 신상품 소개',
    createdAt: '2026-02-10T14:00:00Z',
    status: 'ended',
    orderCount: 8,
    totalAmount: 98400,
  },
]
