export const mockProducts = [
  {
    id: 'p1',
    name: '무르무르 키링 세트',
    option: '노랑',
    price: 12900,
    stock: 100,
  },
  {
    id: 'p1-black',
    name: '무르무르 키링 세트',
    option: '블랙',
    price: 12900,
    stock: 80,
  },
  {
    id: 'p2',
    name: '레트로 스티커팩',
    option: 'A세트',
    price: 4500,
    stock: 50,
  },
  {
    id: 'p2-b',
    name: '레트로 스티커팩',
    option: 'B세트',
    price: 4500,
    stock: 45,
  },
  {
    id: 'p3',
    name: '무르무르 에코백',
    option: '파랑',
    price: 8900,
    stock: 80,
  },
  {
    id: 'p3-pink',
    name: '무르무르 에코백',
    option: '핑크',
    price: 8900,
    stock: 60,
  },
  {
    id: 'p4',
    name: '미니 포스터 세트',
    option: '기본',
    price: 6500,
    stock: 60,
  },
  {
    id: 'p5',
    name: '키티롱다리키링',
    option: '노랑',
    price: 5000,
    stock: 75,
  },
  {
    id: 'p5-pink',
    name: '키티롱다리키링',
    option: '핑크',
    price: 5000,
    stock: 55,
  },
  {
    id: 'p6',
    name: '코지지코지키링',
    option: '블랙',
    price: 11000,
    stock: 45,
  },
  {
    id: 'p7',
    name: '키티퀄팅파우치',
    option: '핑크',
    price: 12000,
    stock: 65,
  },
  {
    id: 'p7-beige',
    name: '키티퀄팅파우치',
    option: '베이지',
    price: 12000,
    stock: 50,
  },
  {
    id: 'p8',
    name: '키티물방울스티커',
    option: '기본',
    price: 13300,
    stock: 90,
  },
  {
    id: 'p9',
    name: '폼폼푸린요리사피규어',
    option: '단품',
    price: 1400,
    stock: 55,
  },
  {
    id: 'p10',
    name: '몬치치피규어S',
    option: '브라운',
    price: 13400,
    stock: 40,
  },
  {
    id: 'p10-pink',
    name: '몬치치피규어S',
    option: '핑크',
    price: 13400,
    stock: 35,
  },
]

export const mockRooms = [
  {
    id: 'room-1',
    title: '2월 15일 저녁 특가방',
    createdAt: '2026-02-15T18:00:00Z',
    status: 'active',
    orderCount: 12,
    totalAmount: 156700,
  },
  {
    id: 'room-2',
    title: '2월 10일 신상품 소개',
    createdAt: '2026-02-10T14:00:00Z',
    status: 'ended',
    orderCount: 8,
    totalAmount: 98400,
  },
]
